name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                 ./gradlew build
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args:
                      pack ./github
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Tests
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args:
                      test ./github
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ORG_NAME: ${{ secrets.ORG_NAME }}
                  USER_REPO_NAME: ${{ secrets.REPO_NAME }}
                  ISSUE_ASSIGNEE: ${{ secrets.ASSIGNEE }}
                  RESOURCE_PATH: ${{ secrets.RESOURCE_PATH }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
                  GITHUB_TOPIC: ${{ secrets.TOPIC }}
                  GITHUB_SECRET: ${{ secrets.SECRET }}
                  GITHUB_CALLBACK: ${{ secrets.CALLBACK }}
                  GITHUB_USERNAME: ${{ secrets.USERNAME }}
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  
